#!/bin/bash

#functions
promptYesNo () {
	while true; do
		echo -n "$1 "
		read answer
		case $answer in
			[Yy]* ) return 1;;
			[Nn]* ) return 0;;
			* ) echo "Please enter either y or n";;
		esac
	done
}

createFromTemplate () {
	envsubst "$@" < varfiles
}

read -p "Enter the name of the new site: " NAME

FILE="/etc/nginx/sites-available/$NAME"

if [ -f $FILE ]; then
	echo "This server block already exists"
	exit
fi

promptYesNo "Is this a single page application? [y/n]: "
singlepage=$?

if [ $singlepage -eq 1 ]; then 
	NOTFOUND="/index.html" 
	promptYesNo "Is this a vue application? [y/n]: "
	vue=$?
else
	NOTFOUND="=404"
fi

read -p "Which port will this run on? " PORT

if [ -z $PORT ]; then 
	TEMPLATE=newsite-default.txt
else
	TEMPLATE=newsite-server.txt
	export PORT
fi

read -p "Enter name of folder (/var/www/) " FNAME

if [ -z $FNAME ]; then 
	FNAME=$NAME
fi

echo $FNAME

echo "Creating site..."
export NAME 
export NOTFOUND
export FNAME

envsubst '$NAME $NOTFOUND $PORT $FNAME' < ~/bin/varfiles/$TEMPLATE | sudo tee $FILE > /dev/null

sudo ln -s $FILE /etc/nginx/sites-enabled/
sudo mkdir /var/www/$FNAME
sudo chown $USER /var/www/$FNAME

read -p "Enter git hub repo--git@github.com:$USER/[ENTERHERE].git [press enter to skip]" repo

if [ -z $repo ] && [ $FNAME == $NAME ]; then
	sudo cp ~/bin/varfiles/newsite-index.html /var/www/$FNAME/index.html
else
	read -p "Enter branch (press enter for default): " branch
	
	#if they did not enter the branch, clone without it
	if [ -z $branch ]; then
		source=~/repos/$repo
		mkdir $source
		git clone git@github.com:$USER/$repo.git $source
	else
		source=~/repos/$repo-$branch
		mkdir $source
		git clone -b $branch git@github.com:$USER/$repo.git $source
	fi
	envsubst '$NAME' < ~/bin/varfiles/newsite-makefile.txt | sudo tee $source/makefile > /dev/null
	sudo echo "makefile" > $source/.gitignore
	
	if [ $vue -eq 1 ]; then
		make pull-vue -C $source
	else
		make pull -C $source
	fi
fi

#Secure the website
sudo certbot --nginx -d $NAME


promptYesNo "Do you want to restart the server? [y/n]: "

if [ $? -eq 1 ]; then
	sudo service nginx reload
fi

echo "Site $NAME created"
echo $FILE
